version: "2.3"
services:
  server-eureka:
    build:
      context: ./roncoo-education-server-eureka
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev'
    image: roncoo-education-server-eureka
    container_name: eureka
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka
    networks:
      - education
    ports:
      - "5761:5761"
  server-config:
    build:
      context: ./roncoo-education-server-config
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=native --info.eureka.host=server-eureka'
    image: roncoo-education-server-config
    container_name: config
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/config:/home/roncoo/education/logs/config
    networks:
      - education
    ports:
      - "5721:5721"
    depends_on:
      - server-eureka
    links:
      - server-eureka
  server-gateway:
    build:
      context: ./roncoo-education-server-gateway
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-server-gateway
    container_name: gateway
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/gateway:/home/roncoo/education/logs/gateway
    networks:
      - education
    ports:
      - "5840:5840"
    depends_on:
      - server-config
    links:
      - server-eureka
  course-service:
    build:
      context: ./roncoo-education-course/roncoo-education-course-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=server-eureka'
    image: roncoo-education-course-service
    container_name: course
    restart: always
    volumes:
      - /home/roncoo/dockers/logs/course:/home/roncoo/education/logs/course
    networks:
      - education
    ports:
      - "5710:5710"
    depends_on:
      - server-config
    links:
      - server-eureka
networks:
  education:
    driver: bridge

## docker build
# mvn clean package dockerfile:build
## docker run
# docker run -p 5761:5761 -v /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka --name eureka -d roncoo-education-server-eureka:8.0.0-RELEASE
