version: '1'
services:
  server-eureka:
    restart: always
    build:
      dockerfile: ./roncoo-education-server-eureka
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=192.168.1.13'
    image: roncoo-education-server-eureka
    volumes:
      - /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka
    networks:
      - edu-net
    ports:
      - "5761:5761"
  server-config:
    restart: always
    build:
      dockerfile: ./roncoo-education-server-config
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev --info.eureka.host=192.168.1.13'
    image: roncoo-education-server-config
      volumes:
        - /home/roncoo/dockers/logs/config:/home/roncoo/education/logs/config
      networks:
        - edu-net
      ports:
        - "5721:5721"
networks:
  edu-net:
    driver: bridge

## docker build
# mvn clean package dockerfile:build

## docker run
# docker run -p 5761:5761 -v /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka --name eureka -d roncoo-education-server-eureka:8.0.0-RELEASE
