version: "2.3"
services:
  server-eureka:
    build:
      context: ./roncoo-education-server-eureka
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=dev'
    image: roncoo-education-server-eureka
    container_name: eureka
    restart: always
    environment:
      JAVA_OPTS: '-Xmn128M -Xmx128M'
      RUN_ARGS: '--spring.profiles.active=dev'
    volumes:
      - /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka
    networks:
      - education
    ports:
      - "5761:5761"
  server-config:
    build:
      context: ./roncoo-education-server-config
      args:
        JAVA_OPTS: '-Xmn128M -Xmx128M'
        RUN_ARGS: '--spring.profiles.active=native --info.eureka.host=server-eureka'
    image: roncoo-education-server-config
    container_name: config
    restart: always
    environment:
      JAVA_OPTS: '-Xmn128M -Xmx128M'
      RUN_ARGS: '--spring.profiles.active=native --info.eureka.host=server-eureka'
    volumes:
      - /home/roncoo/dockers/logs/config:/home/roncoo/education/logs/config
    networks:
      - education
    ports:
      - "5721:5721"
    depends_on:
      - server-eureka
    links:
      - server-eureka
networks:
  education:
    driver: bridge

## docker build
# mvn clean package dockerfile:build
## docker run
# docker run -p 5761:5761 -v /home/roncoo/dockers/logs/eureka:/home/roncoo/education/logs/eureka --name eureka -d roncoo-education-server-eureka:8.0.0-RELEASE
